# Generated by Django 5.2.1 on 2025-07-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreArt', models.CharField(max_length=150, verbose_name='Titre')),
                ('s_titre', models.CharField(max_length=200, verbose_name='Sous-titre')),
                ('slug', models.SlugField(unique=True)),
                ('liste_points', models.TextField(blank=True, help_text='Une ligne par point', verbose_name='Liste des points')),
                ('consernant', models.CharField(max_length=100, verbose_name='Concernant')),
                ('descripArt', models.TextField(verbose_name='Description principale')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Source')),
                ('heur', models.DateTimeField(auto_now=True, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-heur'],
            },
        ),
        migrations.CreateModel(
            name='LettersMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellé', models.CharField(max_length=50)),
                ('pour', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('type_pro', models.CharField(choices=[('design', 'design'), ('dev', 'dev')], default='Logo', max_length=50)),
                ('photo', models.ImageField(upload_to='projets/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('projet_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=70)),
                ('profession', models.CharField(max_length=50)),
                ('commentaire', models.TextField()),
                ('aprouver', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/images')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Légende')),
                ('position', models.CharField(choices=[('haut', 'Haut'), ('milieu', 'Milieu'), ('bas', 'Bas'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Position')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.articles')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projets_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(default='Alt texte', max_length=50)),
                ('Projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.projet')),
            ],
        ),
    ]
