# Generated by Django 5.2.1 on 2025-09-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
