# Generated by Django 5.2.1 on 2025-09-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_projet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='projet_url',
            field=models.URLField(blank=True),
        ),
    ]
