# Generated by Django 5.2.1 on 2025-09-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_projet_projet_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Projet',
            new_name='projet',
        ),
    ]
