# Generated by Django 5.2.1 on 2025-09-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_projet_image_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='type_pro',
            field=models.CharField(choices=[('design', 'Design'), ('dev', 'Développement')], default='design', max_length=50),
        ),
    ]
